# webtaz.conf - Configuration file for WebTaz
PROXY="192.168.1.194:8080"
USE_PROXY="true"
USER_AGENT="Mozilla/5.0 (webtaz)"
LOG_DIR_PREFIX="./output/"
PENTESTER_URL="https://pentester.example.com"
# Misc
TRACEROUTE_PORT=443
TRACEROUTE_MAX_PKTS=10
WAPITI_OUTPUT_FMT="html"
WAPITI_COOKIE_FILE="cookie.txt"
NUCLEI_COOKIE_FILE="cookie-header.txt"
# Cores para output (opcional)
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color
